
//----------------------------------------------------
// The following code was generated by jh-javacup-1.0 20160720
// Thu Jan 24 14:33:40 CST 2019
//----------------------------------------------------

package de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int UNDERSCORE = 2;
  public static final int BANG = 3;
  public static final int AS = 4;
  public static final int ASSERT = 5;
  public static final int CHECKSAT = 6;
  public static final int CONTINUEDEXECUTION = 7;
  public static final int DECLARESORT = 8;
  public static final int DECLAREFUN = 9;
  public static final int DECLARECONST = 10;
  public static final int DEFINESORT = 11;
  public static final int DEFINEFUN = 12;
  public static final int ERRORSYM = 13;
  public static final int EXISTS = 14;
  public static final int EXIT = 15;
  public static final int FALSE = 16;
  public static final int FORALL = 17;
  public static final int GETASSERTIONS = 18;
  public static final int GETASSIGNMENT = 19;
  public static final int GETINFO = 20;
  public static final int GETINTERPOLANTS = 21;
  public static final int GETMODEL = 22;
  public static final int GETOPTION = 23;
  public static final int GETPROOF = 24;
  public static final int GETUNSATCORE = 25;
  public static final int GETVALUE = 26;
  public static final int IMMEDIATEEXIT = 27;
  public static final int INCOMPLETE = 28;
  public static final int LET = 29;
  public static final int LOGIC = 30;
  public static final int NONE = 31;
  public static final int NUMERALSYM = 32;
  public static final int MEMOUT = 33;
  public static final int PAR = 34;
  public static final int POP = 35;
  public static final int PUSH = 36;
  public static final int DECIMALSYM = 37;
  public static final int SAT = 38;
  public static final int SUCCESS = 39;
  public static final int SETLOGIC = 40;
  public static final int SETINFO = 41;
  public static final int SETOPTION = 42;
  public static final int STRINGSYM = 43;
  public static final int THEORY = 44;
  public static final int TRUE = 45;
  public static final int UNKNOWN = 46;
  public static final int UNSUPPORTED = 47;
  public static final int UNSAT = 48;
  public static final int INCLUDE = 49;
  public static final int RESET = 50;
  public static final int RESETASSERTIONS = 51;
  public static final int SIMPLIFY = 52;
  public static final int TIMED = 53;
  public static final int ALLSAT = 54;
  public static final int ECHO = 55;
  public static final int FINDIMPLIEDEQUALITY = 56;
  public static final int CHECKSATASSUMING = 57;
  public static final int GETUNSATASSUMPTIONS = 58;
  public static final int CNAMED = 59;
  public static final int CPATTERN = 60;
  public static final int CSORTSDESCRIPTION = 61;
  public static final int CSORTS = 62;
  public static final int CFUNS = 63;
  public static final int CFUNSDESCRIPTION = 64;
  public static final int CDEFINITION = 65;
  public static final int CEXTENSIONS = 66;
  public static final int CLANGUAGE = 67;
  public static final int CTHEORIES = 68;
  public static final int CNOTES = 69;
  public static final int CVALUES = 70;
  public static final int CDIAGNOSTICOUTPUTCHANNEL = 71;
  public static final int CREGULAROUTPUTCHANNEL = 72;
  public static final int CEXPANDDEFINITIONS = 73;
  public static final int CINTERACTIVEMODE = 74;
  public static final int CPRINTSUCCESS = 75;
  public static final int CVERBOSITY = 76;
  public static final int CPRODUCEASSIGNMENTS = 77;
  public static final int CPRODUCEMODELS = 78;
  public static final int CPRODUCEPROOFS = 79;
  public static final int CPRODUCEUNSATCORES = 80;
  public static final int CRANDOMSEED = 81;
  public static final int CINTERPOLANTCHECKMODE = 82;
  public static final int CSTRONGSIMPLIFIER = 83;
  public static final int CTIMEOUT = 84;
  public static final int CPRODUCEUNSATASSUMPTIONS = 85;
  public static final int SYMBOL = 86;
  public static final int KEYWORD = 87;
  public static final int NUMERAL = 88;
  public static final int DECIMAL = 89;
  public static final int HEXADECIMAL = 90;
  public static final int BINARY = 91;
  public static final int STRING = 92;
  public static final int LPAR = 93;
  public static final int RPAR = 94;
}

