
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 23 02:15:17 CST 2019
//----------------------------------------------------

package org.sosy_lab.cpachecker.util.predicates.precisionConverter;

/** CUP generated interface containing symbol constants. */
public interface FormulaSymbols {
  /* terminals */
  public static final int DECLAREFUN = 2;
  public static final int DECIMAL = 7;
  public static final int SYMBOL = 5;
  public static final int LPAR = 9;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int NUMERAL = 6;
  public static final int error = 1;
  public static final int ASSERT = 4;
  public static final int DEFINEFUN = 3;
  public static final int RPAR = 10;
}

