
//----------------------------------------------------
// The following code was generated by jh-javacup-1.0 20160720
// Thu Jan 24 14:33:41 CST 2019
//----------------------------------------------------

package de.uni_freiburg.informatik.ultimate.smtinterpol.dimacs;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int PROBLEM = 2;
  public static final int CNF = 3;
  public static final int NOT = 4;
  public static final int EOC = 5;
  public static final int NUMBER = 6;
}

